version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "3000:3000"   # app web UI
      - "8123:8123"   # Web UI
      - "3628:3628"   # Torrenting port
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Canada,United States}
      - VPN_PORT_FORWARDING=on
    volumes:
      - ./gluetun:/tmp/gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - <Enter your config volume>:/config
      - <Enter your movie storage volume>:/mnt/movies
      - <Enter your tv storage volume>:/mnt/tv
    environment:
      - TZ=America/Toronto
      - WEBUI_PORT=8123
      - TORRENTING_PORT=3628
      - PUID=<Enter your user ID here>
      - PGID=<Enter your group ID here>
      - UMASK=002
      - DOCKER_MODS=lscr.io/linuxserver/mods:universal-unrar6
    restart: unless-stopped
    network_mode: service:gluetun

  app:
    build:
      context: ./app
    container_name: app
    network_mode: service:gluetun
    user: <Enter your user ID here>:<Enter your group ID here>
    environment:
      - TZ=America/Toronto
      - PYTHONUNBUFFERED=1
      - QBITTORRENT_WEBUI_PORT=8123
      - WEBUI_PORT=3000
      - QBT_USERNAME=${QBT_USERNAME:-admin}
      - QBT_PASSWORD=${QBT_PASSWORD:-adminadmin}
    restart: unless-stopped
    depends_on:
      - qbittorrent # Ensure qBittorrent is ready before starting the app